global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'battery_predictor'
    static_configs:
      - targets: ['host.docker.internal:9091']
        labels:
          service: 'battery-predictor'
